# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='文章名')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='作者')),
                ('summary', models.TextField(verbose_name='简介')),
                ('img', models.ImageField(upload_to='', verbose_name='文章图片')),
                ('counter', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='ArtTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='作品类别')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加的时间')),
                ('modify_time', models.TimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artapp.ArtTag'),
        ),
    ]
